title: neilmunday
email: neilmunday@users.noreply.github.com
description: >- 
  Github web site for Neil Munday
baseurl: ""
url: "https://neilmunday.github.io"
github_username: neilmunday
show_downloads: false

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
exclude:
  - tools/
  - doc/
