title: neilmunday
email: neilmunday@users.noreply.github.com
description: >- 
  Github web site for Neil Munday
baseurl: ""
url: "https://neilmunday.github.io"
github_username: neilmunday

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - tools/
  - doc/
